### ISSUE TITLE
Flex Softbody With Springs

### ISSUE THREAD

**Issue by Adhil-Suresh** [simco50/FluxEngine#5]
Hi i am working on flex with unity engine to create softbody.The problem is it is creating softbody with shape(bones) constraints.Is it possible to create softbody with springs?

**Comment by simco50** [comment]
Hi Adhil,
I'm not sure how the implementation in Unity works so I'm afraid I won't be able to help you.
You might have better luck asking this on the Unity community forums.
Thanks

**Comment by Adhil-Suresh** [comment]
Yeah okey.But  can you tell me the softbody you created using flex is made of springs and particles or particles and bones it would be helpful to me
